apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-lz2u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-lz2u
    app.kubernetes.io/part-of: my-exhort-main
  name: exhort-lz2u0tyl
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: exhort-lz2u
    weight: null
status: {}
