apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-lz2u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-lz2u
    app.kubernetes.io/part-of: my-exhort-main
  name: exhort-lz2u
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: exhort-lz2u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: exhort-lz2u
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bmozaffari-gps-jboss-tenant/my-exhort-main/exhort-lz2u@sha256:6181fdef0c6530c15c55b158d52a22b65186b091d942ec983a578c42a83ab549
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
