apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-lz2u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-lz2u
    app.kubernetes.io/part-of: my-exhort-main
  name: exhort-lz2u
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: exhort-lz2u
status:
  loadBalancer: {}
